### ISSUE TITLE
Installing rapidsms-twilio

### ISSUE THREAD

**Issue by rvr123** [caktus/rapidsms-twilio#7]
Hi all, i installed rapidsms in my local and tested the ping & pong demo. Its works fine. For mobile messages, where the rapidsms twilio is installed? I read the documents but didn't got an idea about installation. 
I want to send message to application and respond to that message.

Thanks.

**Comment by mlavin** [comment]
`rapidsms-twilio` when installed via `pip` will be added to your system or virtualenv site-packages depending on where you are trying to install it.
